resume_categories={
    "Data Science": [
        "machine learning",
        "data analysis",
        "python",
        "statistics",
        "deep learning",
        "pandas",
        "numpy",
        "artificial intelligence",
        "data mining",
        "big data"
    ],
    "Human Resources": [
        "recruitment",
        "talent acquisition",
        "employee relations",
        "performance management",
        "training and development",
        "hr policies",
        "payroll management",
        "compliance",
        "organizational development",
        "hr analytics",
        "employee engagement",
        "conflict resolution",
        "workforce planning",
        "onboarding",
        "offboarding",
        "job analysis",
        "compensation and benefits",
        "labor laws",
        "diversity and inclusion",
        "hr software",
        "hr management systems",
        "people management",
        "soft skills",
        "communication",
        "negotiation",
        "problem solving",
        "time management",
        "adaptability",
        "team collaboration",
        "leadership",
        "empathy",
        "critical thinking",
        "attention to detail",
        "project management",
        "certifications",
        "society for human resource management (SHRM)",
        "certified human resources professional (CHRP)",
        "certified human resources manager (CHRM)",
        "certified professional in learning and performance (CPLP)",
        "certified compensation professional (CCP)",
        "certified benefits professional (CBP)",
        "certified talent acquisition strategist (CTAS)",
        "certified employee benefits specialist (CEBS)",
        "certified diversity and inclusion professional (CDIP)",
        "certified human resources business partner (CHRPB)",
        "certified human resources executive (CHRE)",
        "certified global professional in human resources (GPHR)",
        "certified professional in human resources (PHR)",
        "certified senior professional in human resources (SPHR)",
        "certified talent management practitioner (CTMP)",
    ],
    "Sales and Marketing":[
        "sales",
        "marketing",
        "customer relationship management (CRM)",
        "lead generation",
        "digital marketing",
        "content marketing",
        "social media marketing",
        "email marketing",
        "search engine optimization (SEO)",
        "pay-per-click (PPC)",
        "brand management",
        "market research",
        "sales strategy",
        "negotiation skills",
        "customer service",
        "product knowledge",
        "communication skills",
        "presentation skills",
        "data analysis",
        "analytics tools",
        "google analytics",
        "hubspot",
        "salesforce",
        "microsoft dynamics 365",
        "soft skills",
        "relationship building",
        "problem solving",
        "time management",
        "adaptability",
        "team collaboration",
        "leadership skills",
        "critical thinking",
        "attention to detail",
        "project management",
        "certifications",
        "google ads certification",
        "google analytics certification",
        "hubspot inbound marketing certification",
        "hubspot content marketing certification",
        "hubspot social media certification",
        "hubspot email marketing certification",
        "certified sales professional (CSP)",
        "certified professional sales person (CPSP)",
        "certified sales executive (CSE)",
        "certified marketing professional (CMP)",
        "certified digital marketing professional (CDMP)",
        "certified social media strategist (CSMS)",
        "certified email marketing specialist (CEMS)",
        "certified search engine optimization (SEO) specialist",
        "certified pay-per-click (PPC) specialist",
        "certified brand strategist",
        "certified market research analyst (CMRA)",
        "certified customer experience professional (CCEP)",
        "certified customer service professional (CCSP)",
        "certified customer relationship management (CRM) professional",
        "certified product marketing manager (CPMM)",
        "Digital Marketing"
    ],
    "Software Development": [
        "java",
        "spring boot",
        "software engineering",
        "development",
        "javascript",
        "react",
        "angular",
        "html",
        "css",
        "c#",
        "c++",
        "ruby",
        "docker",
        "kubernetes",
        "rest api",
        "Python",
        "c++",
        "Java script",
        "c#",
        "ruby",
        "php",
        "swift",
        "go",
        "kotlin",
        "HTML",
        "css",
        "react.js",
        "angularJS",
        "node.js",
        "vue.js",
        "Django",
        "ruby on rails",
        "asp.net",
        "flask",
        "sql",
        "mysql",
        "postgresql",
        "mongodb",
        "oracle",
        "sqlite",
        "redis",
        "firebase",
        "elasticsearch",
        "cassandra",
        "git",
        "docker",
        "kubernetes",
        "jenkins",
        "aws",
        "azure",
        "google cloud",
        "tarraform",
        "ansible",
        "webpack",
        "agile methodologies",
        "scrum",
        "test driven development(TDD)",
        "continous integration/continous deployment(ci/cd)",
        "version control",
        "CODE REVIEW",
        "PAIR PROGRAMMING",
        "REFACTORING",
        "DESIGNpatterns",
        "devops",
        "problem-solving",
        "communication",
        "team collaboration",
        "adaptability",
        "time management",
        "critical thinking",
        "leadership",
        "attention to detail",
        "creativity",
        "project management",
        "bachelor's/master's in computer science",
        "certified scrum master",
        "aws certified developer",
        "microsoft certified: Azure developer associate",
        "google professional cloud developer",
        "oracle certified professional",
        "cisco certified network associate (CCNA)",
        "comptia security+",
        "project management professional",
        "certified kubernetes adinistrator",  
    ],
    "Business Analysis": [
        "business analysis",
        "excel",
        "data visualization",
        "power bi",
        "tableau",
        "reporting",
        "business strategy",
        "market research",
        "stakeholder management",
        "requirements gathering",
        "python",
        "R",
        "SQL",
        "Java",
        "SAS",
        "Matlab",
        "data Analysis and Manipulation",
        "Data mining",
        "data cleaning",
        "data wrangling",
        "statistical analysis",
        "predictive modeling",
        "a/b testing",
        "regression analysis",
        "hypothesis testing",
        "data visulasation tools",
        "Qlikview",
        "d3.js",
        "google data studio"
        "database management system",
        "mysql",
        "postgresql",
        "oracle",
        "microsoft sql server",
        "mongodb",
        "big data technologies",
        "hadoop",
        "spark",
        "hive",
        "pig",
        "machine learning framework",
        "scikit-learn",
        "tensorflow",
        "keras",
        "soft skill",
        "analytical thinking",
        "problem solving",
        "attention to details",
        "communication",
        "collaboration",
        "time management",
        "critical thinking",
        "certified analytics professionals",
        "microsoft certified data analyst associate",
        "sas certified data scientist",
        "ibm data science professional certificate"
        "google data analytics professional certificate"
        "financial modelling",
        "risk analysis",
        "portfolio management",
        "customer segmentation",
        "market basket analysis",
        "churn prediction",
        "clinical data analytics",
        "Agile",
        "scrum",
        "waterfall",
        "lean six sigma",
        "sap",
        "salesforce",
        "jira"
    ],
    "DevOps": [
        "devops",
        "continuous integration",
        "continuous deployment",
        "jenkins",
        "git",
        "ansible",
        "terraform",
        "aws",
        "azure",
        "google cloud",
        "ci/cd",
        "shell scripting",
        "linux",
        "configuration management tools",
        "ansible",
        "puppet",
        "chef",
        "infrastructure as code",
        "terraform",
        "cloudformation",
        "cloud platforms",
        "amazon web services",
        "microsoft azure",
        "google cloud platform",
        "openstack",
        "continuous intergration/continous deployment tools",
        "jenkins",
        "gitlabs CI",
        "travis CI",
        "circle CI",
        "version control systems",
        "git",
        "subversion",
        "monitoring and logging tools",
        "prometheus",
        "grafana",
        "elk stack",
        "nagious",
        "scripting and programming languages",
        "python",
        "bash",
        "shell scripting",
        "go",
        "ruby",
        "operating systems",
        "linux",
        "unix",
        "windows server",
        "networking and security",
        "load balancing",
        "firewall management",
        "vpn",
        "ssl/tls",
        "Network protocols",
        "soft skills",
        "collaboration",
        "communication skills",
        "problem solving",
        "adaptability",
        "time management",
        "attention to detail",
        "certifications",
        "aws certified devops engineer",
        "microsoft certified: azure devops engineer expert",
        "google professional devops engineer",
        "docker certified associate",
        "methodologies",
        "agile",
        "scrum",
        "kanban",
        
    ],
    "UI/UX Design": [
        "ui design",
        "ux design",
        "wireframing",
        "prototyping",
        "figma",
        "adobe xd",
        "user research",
        "usability testing",
        "interaction design",
        "visual design",
        "user experience design",
        "user centered design",
        "interaction design",
        "infromation architecture",
        "usability testing",
        "wireframing",
        "prototyping",
        "user research",
        "persona development",
        "journey mapping",
        "heuristic evaluation",
        "user interface design",
        "visual design",
        "responsive design",
        "typography",
        "color theory",
        "oconography",
        "design systems",
        "style guides",
        "high fidelity mockups",
        "interaction patterns",
        "animation design",
        "design tools and software",
        "adobe creative suite",
        "sketch",
        "figma",
        "invision",
        "axure rp",
        "marvel app",
        "bvalsamiq",
        "zeplin",
        "framer",
        "principle",
        "front end development",
        "html/css",
        "javascript",
        "react.js",
        "angularjs",
        "vue.js",
        "bootstrap",
        "jquery",
        "sass/less",
        "responsive framework",
        "cross border compatibility",
        "research and analytical skills",
        "a/b testing",
        "analytics interpretation",
        "heatmaps",
        "usr surveys",
        "focus groups",
        "competitive analysis",
        "data driven design",
        "user feedbak analysis",
        "task analysis",
        "cognitive walkthroughs",
        "softskills",
        "communication skills",
        "collaboration",
        "problem solving",
        "adaptability",
        "time management",
        "attention to detail",
        "empathy",
        "critical thinking",
        "creativity",
        "project management",
        "design thinking",
        "agile",
        "scrum",
        "lean UX",
        "double diamond",
        "human centered design",
        "kanban",
        "user centered design process",
        "kanban",
        "user centered design process",
        "rapid prototyping",
        "service design",
        "Certification and education",
        "bachelor's/master's in design",
        "certified usability analyst",
        "ux certification",
        "human computer interaction",
        "google ux design professional certificate",
        "adobe certificate expert",
        "interaction design foundation certification",
        "safe agile certification",
        "design leadership certification",
        "front end development certification",
    ],
    "Cybersecurity": [
        "cybersecurity",
        "information security",
        "network security",
        "ethical hacking",
        "penetration testing",
        "firewalls",
        "encryption",
        "incident response",
        "security audits",
        "risk assessment"
    ],
    "Project Management": [
        "project management",
        "agile",
        "scrum",
        "kanban",
        "jira",
        "trello",
        "risk management",
        "budgeting",
        "team management",
        "project planning",
        "stakeholder communication"
    ],
    "Marketing": [
        "digital marketing",
        "seo",
        "social media",
        "content creation",
        "email marketing",
        "google analytics",
        "campaign management",
        "branding",
        "ppc",
        "market analysis"
    ],
    "Finance": [
        "accounting",
        "financial analysis",
        "forecasting",
        "budgeting",
        "taxation",
        "investment analysis",
        "risk management",
        "quickbooks",
        "financial modeling",
        "auditing"
    ],
    "Healthcare": [
        "nursing",
        "clinical research",
        "patient care",
        "health informatics",
        "medical coding",
        "epidemiology",
        "pharmaceuticals",
        "public health",
        "biotechnology",
        "healthcare management"
    ],
    "Education": [
        "teaching",
        "curriculum development",
        "lesson planning",
        "classroom management",
        "online teaching",
        "educational technology",
        "academic writing",
        "student counseling",
        "e-learning",
        "training"
    ]
}
