"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 5.1.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""
# Disable auto reloading settings

DATA_UPLOAD_MAX_MEMORY_SIZE = 52428800  # 50 MB
FILE_UPLOAD_MAX_MEMORY_SIZE = 52428800  # 50 MB


from pathlib import Path
import os
# settings.py
import socket
socket.setdefaulttimeout(60)  # Set to 60 seconds
SECURE_SSL_REDIRECT=False

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent # location to store files

print("\n")
print("Path(_file_) is:   ", Path(__file__))
print("Path(_file_).resolve() is:   ", Path(__file__).resolve())
print("Path(_file_).resolve().parent is:   ", Path(__file__).resolve().parent)
print("Path(_file_).resolve().parent.parent is:   ", Path(__file__).resolve().parent.parent)

print("Base directory is:   ", BASE_DIR)


# Media (uploaded files)
MEDIA_URL = '/media/'
print("\n")
print("Media URL is:   ", MEDIA_URL)
print("\n")


MEDIA_ROOT = os.path.join(BASE_DIR, 'data/resumes')
print("The media root is:   ", MEDIA_ROOT)
print("\n")
# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

STATIC_URL = '/static/'
# STATICFILES_DIRS = [
#     os.path.join(BASE_DIR, 'frontend')
# ]

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-2+=k2w)cea-!437@fzp(_0j18kdm=^^3&-u*acma7+ha%qe9dp'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS =['127.0.0.1', 'localhost'] # Allow all hosts for now

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'resume_uploads', # Add the resume_uploads app to the list of installed apps
    'find_Category', # Add the find_Category app to the list of installed apps
    'corsheaders', # Add the corsheaders app to the list of installed apps
    'scrapper',
]


MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'corsheaders.middleware.CorsMiddleware', # Add the CorsMiddleware to the list of middleware
]

SESSION_ENGINE = 'django.contrib.sessions.backends.db'  # Use database-based session storage
SESSION_COOKIE_AGE = 3600  # Session expires in 1 hour
SESSION_SAVE_EVERY_REQUEST = True  # Save session on every request

CORS_ALLOW_ALL_ORIGINS = True

CORS_ALLOWED_ORIGINS = [
    "http://localhost:8000",
    "http://localhost:8001",
    "http://127.0.0.1:5500",  # Example for another allowed frontend (e.g., from Live Server extension)
    "http://127.0.0.1:5501",
    "http://127.0.0.1:5502"
]

X_FRAME_OPTIONS = 'ALLOWALL'

CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'resume_cache',
    }
}



ROOT_URLCONF = 'job_recommender.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'job_recommender.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = False


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

# STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
